### ISSUE TITLE
Impala agent Code Issue

### ISSUE THREAD

**Issue by AizazSharif** [praveen-palanisamy/macad-agents#11]
Hi @praveen-palanisamy ,

I am facing trouble while using Macad-agent impala examples. Even if I lower the resources the code runs but the cars don't move at all in default settings and without any training or crash Carla makes several windows of the environment. 

Is there any way to verify the training of multi-agents through simulation? This way I can re-run the weights and see the results of multi-agent cars.

Thanks

**Comment by praveen-palanisamy** [comment]
Hi @AizazSharif ,
Could you post your training logs to see the status of your training runs?

Once the agents are trained, you can test their learned policies in a single instance of the environment (with rendering enabled) to visualize how the cars are controlled by the Agents.

**Comment by AizazSharif** [comment]
Please find the logs below 

[output.txt](https://github.com/praveen-palanisamy/macad-agents/files/6034189/output.txt)
Also, I used env_config["env"]["render"] = False to disable the rendering but its still enabled.

**Comment by AizazSharif** [comment]
And below are the logs maintained by Macad-agents.

[macad-gym.log](https://github.com/praveen-palanisamy/macad-agents/files/6034195/macad-gym.log)
[server_36779.log](https://github.com/praveen-palanisamy/macad-agents/files/6034196/server_36779.log)
[server_46275.log](https://github.com/praveen-palanisamy/macad-agents/files/6034198/server_46275.log)
[server_51703.log](https://github.com/praveen-palanisamy/macad-agents/files/6034199/server_51703.log)
[server_52455.log](https://github.com/praveen-palanisamy/macad-agents/files/6034200/server_52455.log)

**Comment by praveen-palanisamy** [comment]
Thanks for the logs. Could you post this file?: `/home/aizaz/ray_results/MA-Inde-IMPALA-SSUI3CCARLA/IMPALA_HomoNcomIndePOIntrxMASS3CTWN3-v0_0_2021-02-24_08-37-426o165tlh/error_2021-02-24_08-40-09.txt`
That's where the errors seemed to be logged to.

**Comment by AizazSharif** [comment]
Please find the attached logs you mentioned.

[error_2021-02-24_08-40-09.txt](https://github.com/praveen-palanisamy/macad-agents/files/6041049/error_2021-02-24_08-40-09.txt)

**Comment by AizazSharif** [comment]
From what I have observed, impala code within macad agents stops in each epoch due to shape tensor mismatch even when I run the code on default parameters.

**Comment by praveen-palanisamy** [comment]
It looks like a proper observation pre-processor is not registered with RLLib to resize the observation images (shape: `(168, 168, 3)`) to RLLib's default Conv layer input shape `(84, 84, 3)`. I can push a fix tomorrow.
Meanwhile, you can just change the MACAD-Gym env config ([In this file](https://github.com/praveen-palanisamy/macad-gym/blob/38884ac4bc7fb2e91a865950cff4eeadeed02f60/src/macad_gym/envs/homo/ncom/inde/po/intrx/ma/stop_sign_3c_town03.py#L17-L18) for example) listed below:

                "x_res": 168,
                "y_res": 168,

To `84` for all the Actors.

**Comment by AizazSharif** [comment]
Thanks, I will try this change. 
Also, I wanted to ask is it possible to add your own reward function within macad-agents?

**Comment by praveen-palanisamy** [comment]
No. The Reward functions aren't expected to be modified by/from the Agent algorithm/library.

Reward functions are defined in/by the RL environment. In this case, in the Macad-Gym environments.

**Comment by AizazSharif** [comment]
Makes sense. Thanks for clarifying. 
I will try out the change and let you know.

**Comment by AizazSharif** [comment]
I have tried changing Actors x and y dimensions to 84 but it's still giving an error. 

**ValueError: Cannot feed value of shape (1, 168, 168, 3) for Tensor 'car1/Placeholder:0', which has shape '(?, 84, 84, 3)'** 


[error_2021-02-25_08-39-10.txt](https://github.com/praveen-palanisamy/macad-agents/files/6041259/error_2021-02-25_08-39-10.txt)

**Comment by praveen-palanisamy** [comment]
Hi @AizazSharif ,

I pushed an update that should fix the issue you are facing. Could you try running on your side and confirm?

**Comment by AizazSharif** [comment]
Hi @praveen-palanisamy,

I reinstalled the whole environment and github repo but the error is still there. The logs are from today's testing.

[error_2021-02-27_11-38-21.txt](https://github.com/praveen-palanisamy/macad-agents/files/6054201/error_2021-02-27_11-38-21.txt)

**Comment by AizazSharif** [comment]
I ran python -m macad_agents.rllib.ppo_multiagent_shared_weights and its working fine without errors. But in impala_agent_independent.py the bug might still persist.
